<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Instagram Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5f61c671-a283-476b-8a0f-63686f80cb15</testSuiteGuid>
   <testCaseLink>
      <guid>d2a65c73-25b6-42d4-9799-936781c14f09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'123123'</defaultValue>
         <description></description>
         <id>b47e20c3-fe70-413b-ba8b-558388e8cfe6</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/login_instagram</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>0f96f300-a0c0-4ef4-a319-fe8161f4d866</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Instagram Login Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0f96f300-a0c0-4ef4-a319-fe8161f4d866</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>account</value>
         <variableId>6281d193-649f-4ae3-87ea-7c6d5aade01c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0f96f300-a0c0-4ef4-a319-fe8161f4d866</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b47e20c3-fe70-413b-ba8b-558388e8cfe6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
